// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKns9adpG5yKl6UimG-LY1-w5HGsqwAVQ',
    appId: '1:103039117015:web:da2ded93510db62c35b292',
    messagingSenderId: '103039117015',
    projectId: 'weatherapp-e5a1d',
    authDomain: 'weatherapp-e5a1d.firebaseapp.com',
    storageBucket: 'weatherapp-e5a1d.firebasestorage.app',
    measurementId: 'G-VSW47CZK7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDolKZV7gCivZq7sx2JTCIBevaGYH06nC8',
    appId: '1:103039117015:android:5ecafde32f7267d335b292',
    messagingSenderId: '103039117015',
    projectId: 'weatherapp-e5a1d',
    storageBucket: 'weatherapp-e5a1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSfzHMuHDXnDNf_UnMR2OB9BzKS-Yqb7U',
    appId: '1:103039117015:ios:afdc245ab107792735b292',
    messagingSenderId: '103039117015',
    projectId: 'weatherapp-e5a1d',
    storageBucket: 'weatherapp-e5a1d.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSfzHMuHDXnDNf_UnMR2OB9BzKS-Yqb7U',
    appId: '1:103039117015:ios:afdc245ab107792735b292',
    messagingSenderId: '103039117015',
    projectId: 'weatherapp-e5a1d',
    storageBucket: 'weatherapp-e5a1d.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKns9adpG5yKl6UimG-LY1-w5HGsqwAVQ',
    appId: '1:103039117015:web:b65b9b0504ce5d0335b292',
    messagingSenderId: '103039117015',
    projectId: 'weatherapp-e5a1d',
    authDomain: 'weatherapp-e5a1d.firebaseapp.com',
    storageBucket: 'weatherapp-e5a1d.firebasestorage.app',
    measurementId: 'G-WHMEN69YQQ',
  );
}
