// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUpkHhw4oJdRAaSNTOMkN-4MPqrvcoJng',
    appId: '1:642790156083:web:b852a0ce9348971ad18046',
    messagingSenderId: '642790156083',
    projectId: 'weatherapp-c58f4',
    authDomain: 'weatherapp-c58f4.firebaseapp.com',
    storageBucket: 'weatherapp-c58f4.firebasestorage.app',
    measurementId: 'G-98J7L7P6PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWA91cTkYR9i_LPsYOP9VZHWMvaILcMIo',
    appId: '1:642790156083:android:feb06fee7e616ba9d18046',
    messagingSenderId: '642790156083',
    projectId: 'weatherapp-c58f4',
    storageBucket: 'weatherapp-c58f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ppP0M8-PNSCQKu3tvclyQCYbVs-Ykpk',
    appId: '1:642790156083:ios:fb687587af8703b2d18046',
    messagingSenderId: '642790156083',
    projectId: 'weatherapp-c58f4',
    storageBucket: 'weatherapp-c58f4.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ppP0M8-PNSCQKu3tvclyQCYbVs-Ykpk',
    appId: '1:642790156083:ios:fb687587af8703b2d18046',
    messagingSenderId: '642790156083',
    projectId: 'weatherapp-c58f4',
    storageBucket: 'weatherapp-c58f4.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUpkHhw4oJdRAaSNTOMkN-4MPqrvcoJng',
    appId: '1:642790156083:web:b8c3cc8f54b178d7d18046',
    messagingSenderId: '642790156083',
    projectId: 'weatherapp-c58f4',
    authDomain: 'weatherapp-c58f4.firebaseapp.com',
    storageBucket: 'weatherapp-c58f4.firebasestorage.app',
    measurementId: 'G-YMB8CQHZD9',
  );
}
